#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
mkdir -p $OPENSHIFT_HOMEDIR/app-root/data/public
mkdir -p $OPENSHIFT_HOMEDIR/app-root/data/conf
cp $OPENSHIFT_HOMEDIR/app-root/repo/diy/httpd.conf $OPENSHIFT_HOMEDIR/app-root/data/conf/
sed -i "s/OPENSHIFT_INTERNAL_IP/$OPENSHIFT_INTERNAL_IP/g" $OPENSHIFT_HOMEDIR/app-root/data/conf/httpd.conf
sed -i "s/OPENSHIFT_HOMEDIR/$OPENSHIFT_HOMEDIR/g" $OPENSHIFT_HOMEDIR/app-root/data/conf/httpd.conf
httpd -f $OPENSHIFT_HOMEDIR/app-root/data/conf/httpd.conf
