#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
mkdir -p $OPENSHIFT_HOMEDIR/app-root/data/public
sed -ig 's/OPENSHIFT_INTERNAL_IP/'$OPENSHIFT_INTERNAL_IP'/g' $OPENSHIFT_HOMEDIR/app-root/repo/diy/httpd.conf
sed -ig 's/OPENSHIFT_HOMEDIR/'$OPENSHIFT_HOMEDIR'/g' $OPENSHIFT_HOMEDIR/app-root/repo/diy/httpd.conf
httpd -f $OPENSHIFT_HOMEDIR/app-root/repo/diy/httpd.conf
